#db 설정
spring:
  # 데이터 베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true #들여 쓰기
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect # db마다 해석해줌
    hibernate:
      ddlAuto: create


#로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace